Repository voucherifyio/voucherify-openapi, pull requests merged in 2025-01, with the labels that each got.

#846 PW – RC v20241021
  CONTRIBUTING.md
  changelog/OPEN-API.md
  docs/reference-docs/CAMPAIGNS-Campaign-Object.md
  docs/reference-docs/CUSTOMERS-Customer-Activity-Object.md
  docs/reference-docs/LOYALTIES-Export-Loyalty-Campaign-Point-Expiration.md
  docs/reference-docs/LOYALTIES-List-Loyalty-Card-Point-Expiration.md
  docs/reference-docs/ORDERS-Order-Object.md
  docs/reference-docs/PROMOTIONS-Promotion-Tier-Object.md
  docs/reference-docs/PUBLICATIONS-Publication-Object.md
  docs/reference-docs/QUALIFICATIONS-Qualification-Object.md
  docs/reference-docs/REDEMPTIONS-Redemption-Object.md
  docs/reference-docs/REDEMPTIONS-Rollback-Redemption-Object.md
  docs/reference-docs/VALIDATION-RULES-Validation-Rule-Object.md
  docs/reference-docs/VALIDATIONS-Validation-Object.md
  docs/reference-docs/VOUCHERS-Voucher-Object.md
  production/ENDPOINTS-COVERAGE.md
  production/readOnly-openAPI.json
  reference/OpenAPI.json
  reference/OpenAPIWebhooks.json
  reference/readonly-sdks/java/OpenAPI.json
  reference/readonly-sdks/php/OpenAPI.json
  reference/readonly-sdks/python/OpenAPI.json
  reference/readonly-sdks/ruby/OpenAPI.json
  scripts/prepare-open-api-for-sdk/index.ts
Labels: RELEASE CANDIDATE, READY-TO-MERGE

#850 Update dockerfile ruby by script
  GENERATING-SDKS.md
  package.json
  scripts/update-ruby-dockefile-sdk-version.ts
Labels: READY-TO-MERGE

#855 Management API [Beta} tags
  changelog/OPEN-API.md
  docs/reference-docs/MANAGEMENT-Assign-User.md
  docs/reference-docs/MANAGEMENT-Create-Brand.md
  docs/reference-docs/MANAGEMENT-Create-Custom-Event-Schema.md
  docs/reference-docs/MANAGEMENT-Create-Metadata-Schema.md
  docs/reference-docs/MANAGEMENT-Create-Project.md
  docs/reference-docs/MANAGEMENT-Create-Stacking-Rules.md
  docs/reference-docs/MANAGEMENT-Create-Webhook.md
  docs/reference-docs/MANAGEMENT-Delete-Brand.md
  docs/reference-docs/MANAGEMENT-Delete-Custom-Event-Schema.md
  docs/reference-docs/MANAGEMENT-Delete-Metadata-Schema.md
  docs/reference-docs/MANAGEMENT-Delete-Project.md
  docs/reference-docs/MANAGEMENT-Delete-Stacking-Rules.md
  docs/reference-docs/MANAGEMENT-Delete-Webhook.md
  docs/reference-docs/MANAGEMENT-Get-Brand.md
  docs/reference-docs/MANAGEMENT-Get-Custom-Event-Schema.md
  docs/reference-docs/MANAGEMENT-Get-Metadata-Schema.md
  docs/reference-docs/MANAGEMENT-Get-Project.md
  docs/reference-docs/MANAGEMENT-Get-Stacking-Rules.md
  docs/reference-docs/MANAGEMENT-Get-User.md
  docs/reference-docs/MANAGEMENT-Get-Webhook.md
  docs/reference-docs/MANAGEMENT-Invite-User.md
  docs/reference-docs/MANAGEMENT-List-Brands.md
  docs/reference-docs/MANAGEMENT-List-Custom-Event-Schemas.md
  docs/reference-docs/MANAGEMENT-List-Metadata-Schemas-1.md
  docs/reference-docs/MANAGEMENT-List-Projects.md
  docs/reference-docs/MANAGEMENT-List-Stacking-Rules.md
  docs/reference-docs/MANAGEMENT-List-Users.md
  docs/reference-docs/MANAGEMENT-List-Webhooks.md
  docs/reference-docs/MANAGEMENT-Unassigned-User.md
  docs/reference-docs/MANAGEMENT-Update-Brand.md
  docs/reference-docs/MANAGEMENT-Update-Custom-Event-Schema.md
  docs/reference-docs/MANAGEMENT-Update-Metadata-Schema.md
  docs/reference-docs/MANAGEMENT-Update-Project.md
  docs/reference-docs/MANAGEMENT-Update-Stacking-Rules.md
  docs/reference-docs/MANAGEMENT-Update-User.md
  docs/reference-docs/MANAGEMENT-Update-Webhook.md
Labels: documentation

#854 PW – Pending points
  changelog/OPEN-API.md
  docs/reference-docs/CUSTOMERS-Customer-Activity-Object.md
  docs/reference-docs/LOYALTIES-List-Campaign-Pending-Points.md
  docs/reference-docs/LOYALTIES-List-Member-Pending-Points-1.md
  docs/reference-docs/LOYALTIES-List-Member-Pending-Points.md
  docs/reference-docs/ORDERS-Order-Object.md
  docs/reference-docs/QUALIFICATIONS-Qualification-Object.md
  docs/reference-docs/REDEMPTIONS-Redemption-Object.md
  docs/reference-docs/REDEMPTIONS-Rollback-Redemption-Object.md
  docs/reference-docs/VALIDATIONS-Validation-Object.md
  production/ENDPOINTS-COVERAGE.md
  production/readOnly-openAPI.json
  reference/OpenAPI.json
  reference/readonly-sdks/java/OpenAPI.json
  reference/readonly-sdks/php/OpenAPI.json
  reference/readonly-sdks/python/OpenAPI.json
  reference/readonly-sdks/ruby/OpenAPI.json
  scripts/helpers/get-take-list.ts
Labels: documentation

#857 PW – Pending Points Activate and Cancel
  changelog/OPEN-API.md
  docs/reference-docs/LOYALTIES-Activate-Member-Pending-Points.md
  docs/reference-docs/LOYALTIES-Cancel-Member-Pending-Points.md
  production/ENDPOINTS-COVERAGE.md
  reference/OpenAPI.json
  scripts/helpers/get-take-list.ts
Labels: documentation

#858 Update Security.md
  docs/guides/integration_blueprint/Security.md
Labels: DO NOT MERGE
